version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./infra/gradle/Dockerfile
    container_name: app
    networks:
      - sample-network
    working_dir: /home/gradle/app
    ports:
      - "8888:8080"
    tty: true
    restart: always
    depends_on:
      - db
    environment:
#       application.propertiesの設定情報は無視されます。
      spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
      spring.datasource.url: "jdbc:mysql://db:3306/sampledb"
      spring.datasource.username: "root"
      spring.datasource.password: "root"
      spring.sql.init.mode: "always"
    command: gradle bootRun

  db:
    image: mysql:8.0.33-debian
    container_name: db
    # Todo:設定ファイルボリューム
    # Todo:永続化データボリューム
    networks:
      - sample-network
    ports:
      - "3306:3306"
    expose:
      - "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
      MYSQL_DATABASE: sampledb
      TZ: "Asia/Tokyo"

  web:
    image: nginx:1.24.0-bullseye
    container_name: web-container
    networks:
      - sample-network
    ports:
      - "80:80"
    restart: always
    # Todo:設定ファイルボリューム
# Todo:ネットワーク作成
networks:
  sample-network:


