version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./infra/gradle/Dockerfile
    container_name: app
    networks:
      - sample-network
    ports:
      - "8888:8080"
#    volumes:
#      - ./build/libs/app.jar :/usr/local/bin
    tty: true
    restart: always
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1g
    environment:
      DB_URL: "jdbc:mysql://db:3306/sampledb"

  db:
    image: mysql:8.0.33-debian
    container_name: db
    # Todo:設定ファイルボリューム
    # Todo:永続化データボリューム
    networks:
      - sample-network
    ports:
      - "3306:3306"
    expose:
      - "3306"
    restart: always
    deploy:
      resources:
        limits:
          memory: 1g
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
      MYSQL_DATABASE: sampledb
      TZ: "Asia/Tokyo"
    healthcheck:
      test: [ "CMD", "mysql", "-u", "root", "--password=root"]
      interval: 1s
      timeout: 3s
      retries: 60

  web:
    image: nginx:1.24.0-bullseye
    container_name: web-container
    networks:
      - sample-network
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          memory: 1g
    restart: always
    # Todo:設定ファイルボリューム
# Todo:ネットワーク作成
networks:
  sample-network:


